export interface FinancialTransaction {
	object: 'financialTransaction';
	id: string;
	value: number;
	balance: number;
	type:
		| 'ASAAS_CARD_BALANCE_REFUND'
		| 'ASAAS_CARD_RECHARGE'
		| 'ASAAS_CARD_RECHARGE_REVERSAL'
		| 'ASAAS_CARD_TRANSACTION'
		| 'ASAAS_CARD_TRANSACTION_FEE'
		| 'ASAAS_CARD_TRANSACTION_FEE_REFUND'
		| 'ASAAS_CARD_TRANSACTION_PARTIAL_REFUND'
		| 'ASAAS_CARD_TRANSACTION_REFUND'
		| 'BILL_PAYMENT'
		| 'BILL_PAYMENT_CANCELLED'
		| 'BILL_PAYMENT_FEE'
		| 'BILL_PAYMENT_FEE_CANCELLED'
		| 'BILL_PAYMENT_REFUNDED'
		| 'CANCEL_MOBILE_PHONE_RECHARGE'
		| 'CHARGEBACK'
		| 'CHARGEBACK_REVERSAL'
		| 'CHARGED_FEE_REFUND'
		| 'CONTRACTUAL_EFFECT_SETTLEMENT'
		| 'CONTRACTUAL_EFFECT_SETTLEMENT_REVERSAL'
		| 'CREDIT'
		| 'CREDIT_BUREAU_REPORT'
		| 'CUSTOMER_COMMISSION_CHECKOUT'
		| 'DEBIT'
		| 'DEBIT_REVERSAL'
		| 'DEBT_RECOVERY_NEGOTIATION_FINANCIAL_CHARGES'
		| 'FREE_PAYMENT_USE'
		| 'INSTANT_TEXT_MESSAGE_FEE'
		| 'INTERNAL_TRANSFER_CREDIT'
		| 'INTERNAL_TRANSFER_DEBIT'
		| 'INTERNAL_TRANSFER_REVERSAL'
		| 'INVOICE_FEE'
		| 'MOBILE_PHONE_RECHARGE'
		| 'PARTIAL_PAYMENT'
		| 'PAYMENT_DUNNING_CANCELLATION_FEE'
		| 'PAYMENT_DUNNING_RECEIVED_FEE'
		| 'PAYMENT_DUNNING_RECEIVED_IN_CASH_FEE'
		| 'PAYMENT_DUNNING_REQUEST_FEE'
		| 'PAYMENT_FEE'
		| 'PAYMENT_FEE_REVERSAL'
		| 'PAYMENT_MESSAGING_NOTIFICATION_FEE'
		| 'PAYMENT_RECEIVED'
		| 'PAYMENT_REFUND_CANCELLED'
		| 'PAYMENT_REVERSAL'
		| 'PAYMENT_SMS_NOTIFICATION_FEE'
		| 'PHONE_CALL_NOTIFICATION_FEE'
		| 'PIX_TRANSACTION_DEBIT_REFUND'
		| 'POSTAL_SERVICE_FEE'
		| 'PRODUCT_INVOICE_FEE'
		| 'PROMOTIONAL_CODE_CREDIT'
		| 'PROMOTIONAL_CODE_DEBIT'
		| 'RECEIVABLE_ANTICIPATION_CREDIT'
		| 'RECEIVABLE_ANTICIPATION_DEBIT'
		| 'RECEIVABLE_ANTICIPATION_FEE'
		| 'REFUND_MOBILE_PHONE_RECHARGE'
		| 'REFUND_REQUEST_CANCELLED'
		| 'REFUND_REQUEST_FEE'
		| 'REFUND_REQUEST_FEE_REVERSAL'
		| 'TRANSFER'
		| 'TRANSFER_FEE';
	date: string;
	description: string;
	paymentId: string;
	transferId: string;
	anticipationId: string | null;
	billId: string | null;
	invoiceId: string | null;
	paymentDunningId: string | null;
	creditBureauReportId: string | null;
}
